# Generated by Django 4.0.5 on 2022-06-23 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_image_market_shoe_delete_image11_image_shoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='histogram',
            field=models.DecimalField(decimal_places=2, default=11.11, max_digits=4, verbose_name='Гистограмма'),
            preserve_default=False,
        ),
    ]
