# Generated by Django 4.0.5 on 2022-06-23 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_image_histogram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='decriptor',
            new_name='descriptor',
        ),
        migrations.AlterField(
            model_name='image',
            name='histogram',
            field=models.TextField(verbose_name='Гистограмма'),
        ),
    ]
