# Generated by Django 4.0.5 on 2022-06-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_rename_decriptor_image_descriptor_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageShoe',
        ),
    ]
